import type * as React from 'react';

/** Shared inline styles for the form-based admin screens (Website Content, Meetings). */
export const s = {
  page: { background: '#F5F3FB', minHeight: '100vh', fontFamily: 'var(--font-dm-sans), system-ui, sans-serif' } as React.CSSProperties,
  content: { maxWidth: 900, margin: '0 auto', padding: '40px 24px' } as React.CSSProperties,
  card: {
    background: 'white',
    borderRadius: 12,
    padding: '28px 32px',
    marginBottom: 32,
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  } as React.CSSProperties,
  sectionTitle: {
    fontFamily: 'var(--font-dm-sans), system-ui, sans-serif',
    fontSize: 20,
    fontWeight: 600,
    marginBottom: 20,
    marginTop: 0,
    color: '#1F1535',
  } as React.CSSProperties,
  subheading: {
    fontSize: 13,
    fontWeight: 600,
    color: '#5a5168',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    margin: '0 0 16px',
    fontFamily: 'var(--font-plex-mono), monospace',
  } as React.CSSProperties,
  label: {
    fontFamily: 'var(--font-plex-mono), monospace',
    fontSize: 11,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#5a5168',
    display: 'block',
    marginBottom: 6,
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '10px 14px',
    border: '1.5px solid #d8d3e8',
    borderRadius: 8,
    fontSize: 15,
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  fieldGroup: { marginBottom: 16 } as React.CSSProperties,
  submitBtn: {
    background: '#6D3BE4',
    color: 'white',
    padding: '10px 22px',
    borderRadius: 8,
    border: 'none',
    fontSize: 15,
    cursor: 'pointer',
    fontWeight: 500,
    fontFamily: 'inherit',
  } as React.CSSProperties,
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#c0392b',
    fontSize: 13,
    cursor: 'pointer',
    padding: '4px 8px',
    fontFamily: 'var(--font-plex-mono), monospace',
  } as React.CSSProperties,
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 0',
    borderBottom: '1px solid #ede9f7',
  } as React.CSSProperties,
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 } as React.CSSProperties,
  divider: { borderTop: '1px solid #ede9f7', marginTop: 28, marginBottom: 28 } as React.CSSProperties,
};
